// Generated by generate_templates.py from each renderer's default_layout() - do not edit by hand.
window.CC_TEMPLATE_KINDS = {
 "b50": {
  "title": "Best 50 (/cc-best)",
  "fixedSize": true,
  "defaults": {
   "version": 1,
   "kind": "b50",
   "canvas": [
    6144,
    2508
   ],
   "elements": {
    "icon": {
     "x": 48,
     "y": 24,
     "w": 192,
     "h": 192,
     "visible": true
    },
    "name": {
     "x": 280,
     "y": 64,
     "w": 880,
     "h": 112,
     "visible": true
    },
    "rating_badge": {
     "x": 1208,
     "y": 60,
     "w": 413,
     "h": 120,
     "follow": "name",
     "gap": 48,
     "visible": true
    },
    "stat_total": {
     "x": 5015,
     "y": 56,
     "w": 220,
     "h": 128,
     "visible": true
    },
    "stat_b15": {
     "x": 5235,
     "y": 56,
     "w": 220,
     "h": 128,
     "visible": true
    },
    "stat_b35": {
     "x": 5455,
     "y": 56,
     "w": 220,
     "h": 128,
     "visible": true
    },
    "version_logo": {
     "x": 5739,
     "y": 42,
     "w": 357,
     "h": 156,
     "visible": true
    },
    "section_b35": {
     "x": 44,
     "y": 240,
     "w": 4184,
     "h": 64,
     "visible": true
    },
    "section_b15": {
     "x": 4316,
     "y": 240,
     "w": 1784,
     "h": 64,
     "visible": true
    },
    "divider": {
     "x": 4270,
     "y": 240,
     "w": 4,
     "h": 2206,
     "visible": true
    },
    "grid_b35": {
     "x": 36,
     "y": 304,
     "w": 4200,
     "h": 2150,
     "visible": true
    },
    "grid_b15": {
     "x": 4308,
     "y": 304,
     "w": 1800,
     "h": 2150,
     "visible": true
    }
   },
   "card": {
    "canvas": [
     584,
     414
    ],
    "elements": {
     "type_tag": {
      "x": 16,
      "y": 12,
      "w": 120,
      "h": 40,
      "visible": true
     },
     "level_badge": {
      "x": 408,
      "y": 8,
      "w": 160,
      "h": 52,
      "visible": true
     },
     "title": {
      "x": 16,
      "y": 68,
      "w": 552,
      "h": 40,
      "visible": true
     },
     "card_divider": {
      "x": 16,
      "y": 152,
      "w": 552,
      "h": 4,
      "visible": true
     },
     "jacket": {
      "x": 16,
      "y": 168,
      "w": 180,
      "h": 180,
      "visible": true
     },
     "rank_icon": {
      "x": 216,
      "y": 168,
      "w": 220,
      "h": 76,
      "visible": true
     },
     "achievement": {
      "x": 216,
      "y": 260,
      "w": 300,
      "h": 52,
      "visible": true
     },
     "difficulty_name": {
      "x": 216,
      "y": 316,
      "w": 220,
      "h": 40,
      "visible": true
     },
     "sync_icon": {
      "x": 508,
      "y": 168,
      "w": 60,
      "h": 60,
      "visible": true
     },
     "combo_icon": {
      "x": 436,
      "y": 168,
      "w": 60,
      "h": 60,
      "visible": true
     },
     "rating_value": {
      "x": 388,
      "y": 330,
      "w": 180,
      "h": 80,
      "visible": true
     },
     "rank_number": {
      "x": 16,
      "y": 374,
      "w": 100,
      "h": 36,
      "visible": true
     },
     "card_bg": {
      "x": 0,
      "y": 0,
      "w": 584,
      "h": 414,
      "visible": true
     }
    }
   },
   "colors": {
    "section_old": "#8c96d2",
    "section_new": "#ffb040",
    "divider": "#464858"
   },
   "options": {
    "card_background": true,
    "collapse_badges": true
   }
  },
  "labels": {
   "icon": "Icon",
   "name": "Player name",
   "rating_badge": "Rating badge",
   "stat_total": "Total rating",
   "stat_b15": "B15 total",
   "stat_b35": "B35 total",
   "version_logo": "Version logo",
   "section_b35": "B35 heading",
   "section_b15": "B15 heading",
   "divider": "Divider",
   "grid_b35": "B35 grid",
   "grid_b15": "B15 grid"
  },
  "cardLabels": {
   "type_tag": "DX/STD tag",
   "level_badge": "Level",
   "title": "Title",
   "card_divider": "Divider",
   "jacket": "Jacket",
   "rank_icon": "Rank",
   "achievement": "Achievement",
   "difficulty_name": "Difficulty",
   "sync_icon": "Sync badge",
   "combo_icon": "Combo badge",
   "rating_value": "Rating",
   "rank_number": "#",
   "card_bg": "Card background"
  },
  "resize": {
   "grid_b35": "none",
   "grid_b15": "none",
   "card_divider": "x",
   "card_bg": "none"
  },
  "textElements": [
   "name",
   "section_b15",
   "section_b35",
   "stat_b15",
   "stat_b35",
   "stat_total"
  ],
  "cardTextElements": [
   "achievement",
   "difficulty_name",
   "level_badge",
   "rank_number",
   "rating_value",
   "title",
   "type_tag"
  ],
  "colorLabels": {
   "section_old": "Older-versions heading (B35)",
   "section_new": "Current-version heading (B15)",
   "divider": "Divider line"
  },
  "opacityLabels": {},
  "widthLabels": {},
  "grid": {
   "cell": [
    600,
    430
   ],
   "cellPadding": 8,
   "rows": 5,
   "cols": {
    "grid_b35": 7,
    "grid_b15": 3
   }
  }
 },
 "profile_core": {
  "title": "Profile core (/cc-profile)",
  "fixedSize": true,
  "defaults": {
   "version": 1,
   "kind": "profile_core",
   "canvas": [
    640,
    961
   ],
   "elements": {
    "icon": {
     "x": 20,
     "y": 20,
     "w": 84,
     "h": 84,
     "visible": true
    },
    "name": {
     "x": 120,
     "y": 20,
     "w": 360,
     "h": 40,
     "visible": true
    },
    "play_stats": {
     "x": 480,
     "y": 20,
     "w": 140,
     "h": 30,
     "visible": true
    },
    "title_capsule": {
     "x": 120,
     "y": 70,
     "w": 300,
     "h": 30,
     "visible": true
    },
    "rating_badge": {
     "x": 20,
     "y": 114,
     "w": 138,
     "h": 40,
     "visible": true
    },
    "course_rank": {
     "x": 168,
     "y": 114,
     "w": 34,
     "h": 34,
     "follow": "rating_badge",
     "gap": 10,
     "visible": true
    },
    "class_rank": {
     "x": 210,
     "y": 114,
     "w": 34,
     "h": 34,
     "follow": "course_rank",
     "gap": 8,
     "visible": true
    },
    "star_count": {
     "x": 252,
     "y": 114,
     "w": 100,
     "h": 34,
     "follow": "class_rank",
     "gap": 8,
     "visible": true
    },
    "row_rank_sssp": {
     "x": 20,
     "y": 174,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_rank_sss": {
     "x": 20,
     "y": 238,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_rank_ssp": {
     "x": 20,
     "y": 302,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_rank_ss": {
     "x": 20,
     "y": 366,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_rank_sp": {
     "x": 20,
     "y": 430,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_rank_s": {
     "x": 20,
     "y": 494,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_clear_clear": {
     "x": 20,
     "y": 558,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_dxstar_5": {
     "x": 20,
     "y": 622,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_dxstar_4": {
     "x": 20,
     "y": 686,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_dxstar_3": {
     "x": 20,
     "y": 750,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_dxstar_2": {
     "x": 20,
     "y": 814,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_dxstar_1": {
     "x": 20,
     "y": 878,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_combo_app": {
     "x": 328,
     "y": 174,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_combo_ap": {
     "x": 328,
     "y": 238,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_combo_fcp": {
     "x": 328,
     "y": 302,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_combo_fc": {
     "x": 328,
     "y": 366,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_sync_fdxp": {
     "x": 328,
     "y": 430,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_sync_fdx": {
     "x": 328,
     "y": 494,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_sync_fsp": {
     "x": 328,
     "y": 558,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_sync_fs": {
     "x": 328,
     "y": 622,
     "w": 292,
     "h": 56,
     "visible": true
    },
    "row_sync_sync": {
     "x": 328,
     "y": 686,
     "w": 292,
     "h": 56,
     "visible": true
    }
   },
   "colors": {
    "pill_border": "#0e76b2",
    "pill_fill": "#48bfee",
    "pill_text": "#0d375c",
    "pill_text_outline": "#141414"
   },
   "widths": {
    "pill_text_outline_width": 0
   },
   "opacities": {
    "pill_background": 1.0,
    "pill_icon": 1.0,
    "pill_text": 1.0
   },
   "options": {
    "count_pill_background": true
   }
  },
  "labels": {
   "icon": "Icon",
   "name": "Player name",
   "play_stats": "Play counts",
   "title_capsule": "Title",
   "rating_badge": "Rating badge",
   "course_rank": "Course rank",
   "class_rank": "Class rank",
   "star_count": "Star count",
   "row_rank_sssp": "Row: SSS+",
   "row_rank_sss": "Row: SSS",
   "row_rank_ssp": "Row: SS+",
   "row_rank_ss": "Row: SS",
   "row_rank_sp": "Row: S+",
   "row_rank_s": "Row: S",
   "row_clear_clear": "Row: CLEAR",
   "row_dxstar_5": "Row: DX STAR 5",
   "row_dxstar_4": "Row: DX STAR 4",
   "row_dxstar_3": "Row: DX STAR 3",
   "row_dxstar_2": "Row: DX STAR 2",
   "row_dxstar_1": "Row: DX STAR 1",
   "row_combo_app": "Row: AP+",
   "row_combo_ap": "Row: AP",
   "row_combo_fcp": "Row: FC+",
   "row_combo_fc": "Row: FC",
   "row_sync_fdxp": "Row: FDX+",
   "row_sync_fdx": "Row: FDX",
   "row_sync_fsp": "Row: FS+",
   "row_sync_fs": "Row: FS",
   "row_sync_sync": "Row: SYNC PLAY"
  },
  "cardLabels": null,
  "resize": {},
  "textElements": [],
  "cardTextElements": [],
  "colorLabels": {
   "pill_border": "Count pill border",
   "pill_fill": "Count pill fill",
   "pill_text": "Count pill text",
   "pill_text_outline": "Count text outline"
  },
  "opacityLabels": {
   "pill_background": "Count pill background",
   "pill_icon": "Count tier icon",
   "pill_text": "Count text"
  },
  "widthLabels": {
   "pill_text_outline_width": "Count text outline width"
  }
 },
 "profile_extra": {
  "title": "Profile extra (/cc-profile view:extra)",
  "fixedSize": false,
  "defaults": {
   "version": 1,
   "kind": "profile_extra",
   "canvas": [
    640,
    837
   ],
   "elements": {
    "icon": {
     "x": 24,
     "y": 13,
     "w": 64,
     "h": 64,
     "visible": true
    },
    "name": {
     "x": 104,
     "y": 27,
     "w": 512,
     "h": 40,
     "visible": true
    },
    "cp_block": {
     "x": 24,
     "y": 90,
     "w": 592,
     "h": 90,
     "visible": true
    },
    "mile_block": {
     "x": 24,
     "y": 180,
     "w": 592,
     "h": 70,
     "visible": true
    },
    "mission_list": {
     "x": 24,
     "y": 250,
     "w": 592,
     "h": 230,
     "visible": true
    },
    "tickets_header": {
     "x": 24,
     "y": 494,
     "w": 200,
     "h": 34,
     "visible": true
    },
    "ticket_list": {
     "x": 24,
     "y": 528,
     "w": 592,
     "h": 228,
     "visible": true
    },
    "presents": {
     "x": 24,
     "y": 770,
     "w": 300,
     "h": 40,
     "visible": true
    }
   },
   "colors": {
    "cp_bar_fill": "#40c8ff",
    "cp_bar_overflow": "#ff8c3c",
    "cp_bar_track": "#32323e",
    "mission_row": "#262630",
    "mission_row_cleared": "#283c2c",
    "mission_border": "#373744",
    "mission_accent": "#ffdd33",
    "mission_text": "#96969e"
   },
   "options": {
    "compact_lists": true
   }
  },
  "labels": {
   "icon": "Icon",
   "name": "Player name",
   "cp_block": "Class point bar",
   "mile_block": "maimille + mission status",
   "mission_list": "Missions",
   "tickets_header": "TICKETS heading",
   "ticket_list": "Tickets",
   "presents": "Presents count"
  },
  "cardLabels": null,
  "resize": {
   "cp_block": "x",
   "mile_block": "x",
   "mission_list": "x",
   "ticket_list": "x"
  },
  "textElements": [],
  "cardTextElements": [],
  "colorLabels": {
   "cp_bar_fill": "Class point bar",
   "cp_bar_overflow": "Class point overflow",
   "cp_bar_track": "Class point bar background",
   "mission_row": "Mission row",
   "mission_row_cleared": "Cleared mission row",
   "mission_border": "Mission row border",
   "mission_accent": "Mission accent (gold)",
   "mission_text": "Pending mission text"
  },
  "opacityLabels": {},
  "widthLabels": {}
 }
};
