import io

from PIL import Image, ImageDraw, ImageFont

from circlechiffon.renderers.b50 import (
    FONT_DIR,
    RATING_ACCENT_COLOR,
    _TIER_COLORS,
    _draw_guide_box,
    _fit_font,
    _hex_to_rgb,
    _paste_icon,
    _paste_rating_badge,
    _paste_scaled,
    _rounded_mask,
    _scale_to_height,
    _truncate_to_width,
)
from circlechiffon.types import Profile, ProfileExtras

_JP_BOLD = str(FONT_DIR / "NotoSansJP-Bold.ttf")
_JP_MEDIUM = str(FONT_DIR / "NotoSansJP-Medium.ttf")
_INTER_REGULAR = str(FONT_DIR / "Inter_28pt-Regular.ttf")
_INTER_BOLD = str(FONT_DIR / "Inter_28pt-Bold.ttf")

FONT_HEADER_NAME = ImageFont.truetype(_JP_BOLD, 34)
FONT_HEADER_STAT_LABEL = ImageFont.truetype(_INTER_REGULAR, 14)
FONT_FOOTER = ImageFont.truetype(_INTER_REGULAR, 13)
FONT_TIER_TITLE = ImageFont.truetype(_JP_BOLD, 16)
FONT_GRID_COUNT = ImageFont.truetype(_INTER_BOLD, 15)
FONT_GRID_LABEL = ImageFont.truetype(_INTER_REGULAR, 11)
FONT_PILL_COUNT = ImageFont.truetype(_INTER_BOLD, 17)
FONT_SECTION_TITLE = ImageFont.truetype(_JP_BOLD, 20)
FONT_BODY = ImageFont.truetype(_JP_MEDIUM, 16)
FONT_BODY_SMALL = ImageFont.truetype(_JP_MEDIUM, 14)
FONT_MILE = ImageFont.truetype(_INTER_BOLD, 16)

BACKGROUND_COLOR = (24, 24, 32)
FOOTER_HEIGHT = 27
FOOTER_TEXT = "Generated by CiRCLE Chiffon - data from maimai DX NET // cc.etangaming.xyz // etan • etangaming123 • etangamingxyz"

HEADER_HEIGHT_CORE = 174
ICON_SIZE = 84

# render_profile_core is a vertical rectangle, matching the real playerData
# page's own music-count list layout: two side-by-side columns, each a
# vertical stack of rows (colored tier badge + a rounded "pill" holding the
# earned/total count), rather than a flat icon-on-top grid.
CORE_CANVAS_WIDTH = 640
GRID_PAD = 20
GRID_COL_GAP = 16
GRID_ICON_BOX = 56
GRID_ICON_PILL_GAP = 8
GRID_ROW_H = 56
GRID_ROW_GAP = 8
GRID_COLUMN_WIDTH = (CORE_CANVAS_WIDTH - GRID_PAD * 2 - GRID_COL_GAP) // 2
GRID_PILL_WIDTH = GRID_COLUMN_WIDTH - GRID_ICON_BOX - GRID_ICON_PILL_GAP

# left column: rank tiers (highest first) + clear + dxstar (5 down to 1) -
# matches the real page's left-hand list top to bottom. Explicit order since
# dxstar tiers aren't contiguous in the page's own DOM order.
_LEFT_ORDER = [
    ("rank", "sssp"), ("rank", "sss"), ("rank", "ssp"), ("rank", "ss"), ("rank", "sp"), ("rank", "s"),
    ("clear", "clear"),
    ("dxstar", "5"), ("dxstar", "4"), ("dxstar", "3"), ("dxstar", "2"), ("dxstar", "1"),
]
# right column: combo tiers then sync tiers - matches the real page's
# right-hand list top to bottom (AP+, AP, FC+, FC, FDX+, FDX, FS+, FS, Sync Play).
_RIGHT_ORDER = [
    ("combo", "app"), ("combo", "ap"), ("combo", "fcp"), ("combo", "fc"),
    ("sync", "fdxp"), ("sync", "fdx"), ("sync", "fsp"), ("sync", "fs"), ("sync", "sync"),
]
_LEFT_ORDER_INDEX = {key: i for i, key in enumerate(_LEFT_ORDER)}
_RIGHT_ORDER_INDEX = {key: i for i, key in enumerate(_RIGHT_ORDER)}

GRID_ROWS = max(len(_LEFT_ORDER), len(_RIGHT_ORDER))
GRID_HEIGHT = GRID_ROWS * GRID_ROW_H + (GRID_ROWS - 1) * GRID_ROW_GAP

CANVAS_HEIGHT_CORE = HEADER_HEIGHT_CORE + GRID_HEIGHT + FOOTER_HEIGHT

_PILL_BORDER_COLOR = (14, 118, 178)
_PILL_FILL_COLOR = (72, 191, 238)
_PILL_TEXT_COLOR = (13, 55, 92)


def _paste_icon_centered(
    base: Image.Image, icon_bytes: bytes | None, center_x: int, y: int, target_height: int, max_width: int | None = None
) -> int:
    """Like b50._paste_icon, but centers the pasted icon horizontally on
    center_x instead of anchoring its left edge at a fixed position. Badge
    plaques aren't square, so anchoring at `center_x - target_height / 2`
    (assuming pasted width always equals target_height) puts non-square
    icons visibly off-center - this computes the real post-resize width
    first. If `max_width` is given and the height-based width would exceed
    it, the icon is scaled down further (preserving aspect) to fit - some
    badge plaques (e.g. CLEAR) are wide enough that a height-only target
    still overflows a narrow grid cell. Returns the width used (0 if no
    icon)."""
    if not icon_bytes:
        return 0
    try:
        with Image.open(io.BytesIO(icon_bytes)) as icon:
            icon = icon.convert("RGBA")
            bbox = icon.getbbox()
            if bbox:
                icon = icon.crop(bbox)
            w = round(icon.width * target_height / icon.height)
            h = target_height
            if max_width is not None and w > max_width:
                h = round(h * max_width / w)
                w = max_width
            icon = icon.resize((w, h), Image.Resampling.LANCZOS)
            base.paste(icon, (round(center_x - w / 2), y), icon)
            return w
    except Exception:
        return 0


def _draw_footer(image: Image.Image, draw: ImageDraw.ImageDraw, canvas_h: int, canvas_w: int) -> None:
    footer_y = canvas_h - FOOTER_HEIGHT
    draw.rectangle([(0, footer_y), (canvas_w, canvas_h)], fill=(0, 0, 0, 120))
    footer_text = _truncate_to_width(draw, FOOTER_TEXT, FONT_FOOTER, canvas_w - 48)
    draw.text((24, footer_y + 6), footer_text, font=FONT_FOOTER, fill=(200, 200, 205))


def _draw_title_capsule(
    image: Image.Image,
    draw: ImageDraw.ImageDraw,
    title: str | None,
    title_tier: str | None,
    pos: tuple[int, int],
    box_w: int,
    box_h: int,
) -> None:
    """Hand-drawn gradient capsule, same convention as /cc-display - the
    real site has no image asset for the title/trophy banner at all (it's
    CSS-styled text), so both renderers draw it instead of sourcing one."""
    x, y = pos
    _light_hex, mid_hex, dark_hex = _TIER_COLORS.get(title_tier or "", _TIER_COLORS["Gold"])
    radius = box_h // 2
    draw.rounded_rectangle([(x, y), (x + box_w, y + box_h)], radius=radius, fill=_hex_to_rgb(dark_hex))
    inset = 3
    draw.rounded_rectangle(
        [(x + inset, y + inset), (x + box_w - inset, y + box_h - inset)],
        radius=max(radius - inset, 2),
        fill=_hex_to_rgb(mid_hex),
    )
    if title:
        font = _fit_font(draw, title, _JP_BOLD, box_w - 24, box_h - 12)
        text_w = draw.textlength(title, font=font)
        text = title if text_w <= box_w - 24 else _truncate_to_width(draw, title, font, box_w - 24)
        text_w = draw.textlength(text, font=font)
        bbox = draw.textbbox((0, 0), text, font=font)
        text_h = bbox[3] - bbox[1]
        draw.text(
            (x + (box_w - text_w) / 2, y + (box_h - text_h) / 2 - bbox[1]),
            text,
            font=font,
            fill=_hex_to_rgb(dark_hex),
        )


def _draw_count_pill(
    draw: ImageDraw.ImageDraw, x: int, y: int, w: int, h: int, text: str, font: ImageFont.FreeTypeFont
) -> None:
    """Light-blue rounded "pill" holding a right-aligned count, matching the
    real playerData page's own music-count rows (a colored tier badge next
    to a blue capsule, not an icon-over-text grid cell)."""
    radius = h // 2
    draw.rounded_rectangle([(x, y), (x + w, y + h)], radius=radius, fill=_PILL_BORDER_COLOR)
    inset = 3
    draw.rounded_rectangle(
        [(x + inset, y + inset), (x + w - inset, y + h - inset)],
        radius=max(radius - inset, 2),
        fill=_PILL_FILL_COLOR,
    )
    text_w = draw.textlength(text, font=font)
    bbox = draw.textbbox((0, 0), text, font=font)
    text_h = bbox[3] - bbox[1]
    draw.text((x + w - 14 - text_w, y + (h - text_h) / 2 - bbox[1]), text, font=font, fill=_PILL_TEXT_COLOR)


def render_profile_core(
    *,
    profile: Profile,
    icon_bytes: bytes | None,
    course_rank_bytes: bytes | None,
    class_rank_bytes: bytes | None,
    rating_badge_bytes: bytes | None,
    badge_icons: dict[str, bytes],
    output,
) -> None:
    """Synchronous - CPU-bound Pillow work. Call via asyncio.to_thread().
    Matches the "core" stats shown on maimai DX NET's Player's Data page:
    name/title/rating/rank badges/star count/play counts, plus the full
    21-tier music clear-count grid. All image params are optional and
    degrade gracefully to a placeholder / text-only fallback."""
    badge_icons = badge_icons or {}
    image = Image.new("RGB", (CORE_CANVAS_WIDTH, CANVAS_HEIGHT_CORE), BACKGROUND_COLOR)
    draw = ImageDraw.Draw(image)

    pad = GRID_PAD
    right_edge = CORE_CANVAS_WIDTH - pad

    icon_x, icon_y = pad, pad
    # slight round, not a full circle - same convention as /cc-display's icon.
    icon_mask = _rounded_mask((ICON_SIZE, ICON_SIZE), 10)
    pasted_icon = False
    if icon_bytes:
        try:
            with Image.open(io.BytesIO(icon_bytes)) as src:
                scaled = _scale_to_height(src.convert("RGBA"), ICON_SIZE)
                left = max(0, (scaled.width - ICON_SIZE) // 2)
                cropped = scaled.crop((left, 0, left + ICON_SIZE, ICON_SIZE))
                image.paste(cropped, (icon_x, icon_y), icon_mask)
                pasted_icon = True
        except Exception:
            pasted_icon = False
    if not pasted_icon:
        placeholder = Image.new("RGB", (ICON_SIZE, ICON_SIZE), (200, 200, 205))
        image.paste(placeholder, (icon_x, icon_y), icon_mask)

    content_x = icon_x + ICON_SIZE + 16

    # small right-aligned play-count stats, stacked above the name - width
    # reserved first so the (possibly long) display name truncates around
    # them instead of running underneath.
    stats = [("Total Plays", profile.total_plays), ("This Version", profile.current_version_plays)]
    stat_lines = [f"{label}: {value:,}" if value is not None else f"{label}: -" for label, value in stats]
    max_stat_w = max((draw.textlength(t, font=FONT_GRID_LABEL) for t in stat_lines), default=0)
    stat_y = pad
    for text in stat_lines:
        text_w = draw.textlength(text, font=FONT_GRID_LABEL)
        draw.text((right_edge - text_w, stat_y), text, font=FONT_GRID_LABEL, fill=(180, 180, 190))
        stat_y += 15

    name_max_w = max(40, right_edge - max_stat_w - 12 - content_x)
    name = _truncate_to_width(draw, profile.display_name, FONT_HEADER_NAME, name_max_w)
    draw.text((content_x, icon_y), name, font=FONT_HEADER_NAME, fill=(255, 255, 255))

    # title capsule, below the name - still within the icon's height so it
    # doesn't collide with the rating/rank/star row underneath. FONT_HEADER_NAME
    # is 34pt with real ink extending to ~47px below its anchor, so the capsule
    # needs more clearance than the font's point size alone suggests.
    capsule_y = icon_y + 50
    capsule_w = min(300, right_edge - content_x)
    _draw_title_capsule(image, draw, profile.title, profile.title_tier, (content_x, capsule_y), capsule_w, 30)

    # rating pill + rank badges + star count, full-width row below the icon
    row_y = icon_y + ICON_SIZE + 10
    rating_text = str(profile.rating) if profile.rating is not None else "?"
    row_x = pad
    rating_w = _paste_rating_badge(image, draw, rating_badge_bytes, rating_text, (row_x, row_y), 40, RATING_ACCENT_COLOR)
    if rating_w == 0:
        label = f"Rating {rating_text}"
        draw.text((row_x, row_y + 10), label, font=FONT_HEADER_STAT_LABEL, fill=(200, 200, 205))
        rating_w = draw.textlength(label, font=FONT_HEADER_STAT_LABEL)
    row_x += rating_w + 10
    used = _paste_scaled(image, course_rank_bytes, (row_x, row_y), 34)
    row_x += used + (8 if used else 0)
    used = _paste_scaled(image, class_rank_bytes, (row_x, row_y), 34)
    row_x += used + (8 if used else 0)
    used = _paste_icon(image, badge_icons.get("misc:star"), (row_x, row_y + 8), 22)
    row_x += used + (4 if used else 0)
    star_text = f"×{profile.star_count:,}" if profile.star_count is not None else "×-"
    draw.text((row_x, row_y + 10), star_text, font=FONT_HEADER_STAT_LABEL, fill=(220, 220, 225))

    # music clear-count list - two side-by-side columns, each a vertical
    # stack of rows (colored tier badge + a blue count pill), matching the
    # real playerData page's own layout rather than a flat icon-grid.
    grid_top = HEADER_HEIGHT_CORE
    left_entries = sorted(
        (e for e in profile.music_counts if e.category in ("rank", "clear", "dxstar")),
        key=lambda e: _LEFT_ORDER_INDEX.get((e.category, e.tag), len(_LEFT_ORDER)),
    )
    right_entries = sorted(
        (e for e in profile.music_counts if e.category in ("combo", "sync")),
        key=lambda e: _RIGHT_ORDER_INDEX.get((e.category, e.tag), len(_RIGHT_ORDER)),
    )
    for col_x0, entries in ((pad, left_entries), (pad + GRID_COLUMN_WIDTH + GRID_COL_GAP, right_entries)):
        for i, entry in enumerate(entries):
            row_y2 = grid_top + i * (GRID_ROW_H + GRID_ROW_GAP)
            icon_bytes_for_tier = badge_icons.get(f"{entry.category}:{entry.tag}")
            icon_center_x = col_x0 + GRID_ICON_BOX // 2
            # the CLEAR badge's source image is a much wider plaque than the
            # rank/combo/sync/dxstar icons, so pasting it at the same target
            # height as the rest makes it look oversized in its narrow box.
            icon_target_h = 26 if entry.category == "clear" else 42
            icon_y2 = row_y2 + (GRID_ROW_H - icon_target_h) // 2
            used = _paste_icon_centered(image, icon_bytes_for_tier, icon_center_x, icon_y2, icon_target_h, GRID_ICON_BOX - 6)
            if used == 0:
                # no icon available (e.g. remote fetch failed) - fall back to
                # a plain text tag label so the row still identifies its tier.
                label = entry.tag.upper()
                label_w = draw.textlength(label, font=FONT_GRID_LABEL)
                draw.text(
                    (col_x0 + (GRID_ICON_BOX - label_w) / 2, row_y2 + (GRID_ROW_H - 11) / 2),
                    label, font=FONT_GRID_LABEL, fill=(200, 200, 205),
                )
            pill_x = col_x0 + GRID_ICON_BOX + GRID_ICON_PILL_GAP
            count_text = f"{entry.earned:,}/{entry.total:,}" if entry.earned is not None and entry.total is not None else "-"
            _draw_count_pill(draw, pill_x, row_y2, GRID_PILL_WIDTH, GRID_ROW_H, count_text, FONT_PILL_COUNT)

    _draw_footer(image, draw, CANVAS_HEIGHT_CORE, CORE_CANVAS_WIDTH)
    image.save(output, "PNG", compress_level=3)
    output.seek(0)


# narrower than CANVAS_WIDTH on purpose: unlike render_profile_core's
# side-by-side grid, this view's content is a single vertical column, so a
# tall/thin canvas reads better than the shared 1500px-wide one.
EXTRAS_CANVAS_WIDTH = 640

_EXTRA_HEADER_H = 90
_EXTRA_ICON_SIZE = 64
_CP_SECTION_H = 90
_MILE_HEADER_H = 70
_MISSION_ROW_H = 46
_TICKETS_HEADER_H = 34
_TICKET_ROW_H = 76
_INTIMATE_H = 40
_SECTION_GAP = 14


def render_profile_core_template(output) -> None:
    """Synchronous, no live data needed. Renders a transparent-background
    guide PNG at the exact "core" /cc-profile canvas size, with labeled
    outline boxes at every position render_profile_core() actually draws
    content - including every grid cell, labeled by its (category, tag) -
    meant to be opened in an external image editor to design a background
    around the real content instead of guessing at its layout."""
    image = Image.new("RGBA", (CORE_CANVAS_WIDTH, CANVAS_HEIGHT_CORE), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    pad = GRID_PAD
    right_edge = CORE_CANVAS_WIDTH - pad
    icon_x, icon_y = pad, pad
    _draw_guide_box(draw, (icon_x, icon_y, icon_x + ICON_SIZE, icon_y + ICON_SIZE), f"ICON {ICON_SIZE}x{ICON_SIZE}")

    content_x = icon_x + ICON_SIZE + 16
    stat_x = right_edge
    for label in ("Total Plays", "This Version"):
        block_w = 110
        stat_x -= block_w
        _draw_guide_box(draw, (stat_x, pad, stat_x + block_w, pad + 30), f"STAT: {label}")

    _draw_guide_box(draw, (content_x, icon_y, stat_x - 12, icon_y + 30), "PLAYER NAME")

    capsule_y = icon_y + 50
    _draw_guide_box(draw, (content_x, capsule_y, content_x + 300, capsule_y + 30), "TITLE CAPSULE")

    row_y = icon_y + ICON_SIZE + 10
    _draw_guide_box(draw, (pad, row_y, pad + 100, row_y + 40), "RATING BADGE", color=(0, 200, 255))
    row_x = pad + 100 + 10
    _draw_guide_box(draw, (row_x, row_y, row_x + 34, row_y + 34), "COURSE RANK", color=(0, 200, 255))
    row_x += 34 + 8
    _draw_guide_box(draw, (row_x, row_y, row_x + 34, row_y + 34), "CLASS RANK", color=(0, 200, 255))
    row_x += 34 + 8
    _draw_guide_box(draw, (row_x, row_y + 8, row_x + 90, row_y + 30), "STAR COUNT", color=(0, 200, 255))

    # same category universe/order the real render uses.
    grid_top = HEADER_HEIGHT_CORE
    for col_x0, tags in ((pad, _LEFT_ORDER), (pad + GRID_COLUMN_WIDTH + GRID_COL_GAP, _RIGHT_ORDER)):
        for i, (category, tag) in enumerate(tags):
            row_y2 = grid_top + i * (GRID_ROW_H + GRID_ROW_GAP)
            _draw_guide_box(draw, (col_x0, row_y2, col_x0 + GRID_ICON_BOX, row_y2 + GRID_ROW_H), f"{category}:{tag} icon", color=(0, 200, 255))
            pill_x = col_x0 + GRID_ICON_BOX + GRID_ICON_PILL_GAP
            _draw_guide_box(draw, (pill_x, row_y2, pill_x + GRID_PILL_WIDTH, row_y2 + GRID_ROW_H), f"{category}:{tag} pill")

    _draw_guide_box(draw, (0, CANVAS_HEIGHT_CORE - FOOTER_HEIGHT, CORE_CANVAS_WIDTH, CANVAS_HEIGHT_CORE), "FOOTER")

    image.save(output, "PNG", compress_level=3)
    output.seek(0)


def render_profile_extras(
    *,
    profile: Profile,
    extras: ProfileExtras,
    icon_bytes: bytes | None,
    ticket_image_bytes: list[bytes | None],
    output,
) -> None:
    """Synchronous - CPU-bound Pillow work. Call via asyncio.to_thread().
    Renders CP progress, maimile count, missions, tickets, and intimate
    item count - fully separate from render_profile_core's stats, per the
    "extra" /cc-profile view (mutually exclusive with "core", not
    additive)."""
    canvas_h = (
        _EXTRA_HEADER_H
        + _CP_SECTION_H
        + _MILE_HEADER_H
        + len(extras.missions) * _MISSION_ROW_H
        + _SECTION_GAP
        + _TICKETS_HEADER_H
        + max(len(extras.tickets), 1) * _TICKET_ROW_H
        + _SECTION_GAP
        + _INTIMATE_H
        + FOOTER_HEIGHT
    )
    image = Image.new("RGB", (EXTRAS_CANVAS_WIDTH, canvas_h), BACKGROUND_COLOR)
    draw = ImageDraw.Draw(image)

    pad = 24
    y = 0

    # header: icon + name only - no rating/title/ranks, this view is fully
    # separate from the core stats view.
    # slight round, not a full circle - same convention as /cc-display's icon.
    icon_mask = _rounded_mask((_EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE), 10)
    icon_y = (_EXTRA_HEADER_H - _EXTRA_ICON_SIZE) // 2
    pasted_icon = False
    if icon_bytes:
        try:
            with Image.open(io.BytesIO(icon_bytes)) as src:
                scaled = _scale_to_height(src.convert("RGBA"), _EXTRA_ICON_SIZE)
                left = max(0, (scaled.width - _EXTRA_ICON_SIZE) // 2)
                cropped = scaled.crop((left, 0, left + _EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE))
                image.paste(cropped, (pad, icon_y), icon_mask)
                pasted_icon = True
        except Exception:
            pasted_icon = False
    if not pasted_icon:
        placeholder = Image.new("RGB", (_EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE), (200, 200, 205))
        image.paste(placeholder, (pad, icon_y), icon_mask)
    name_x = pad + _EXTRA_ICON_SIZE + 16
    name_text = _truncate_to_width(draw, profile.display_name, FONT_HEADER_NAME, EXTRAS_CANVAS_WIDTH - pad - name_x)
    draw.text((name_x, icon_y + 14), name_text, font=FONT_HEADER_NAME, fill=(255, 255, 255))
    y += _EXTRA_HEADER_H

    # CP (class point) section - hand-drawn bar, no gauge/meter image asset
    # (the real site's version is CSS clip-rect masked, not a flat image).
    draw.text((pad, y + 6), "CLASS POINT", font=FONT_SECTION_TITLE, fill=(255, 255, 255))
    cp_current, cp_required = extras.cp_current, extras.cp_required
    cp_text = f"{cp_current if cp_current is not None else '-'} / {cp_required if cp_required is not None else '-'} CP"
    cp_text_w = draw.textlength(cp_text, font=FONT_BODY)
    draw.text((EXTRAS_CANVAS_WIDTH - pad - cp_text_w, y + 10), cp_text, font=FONT_BODY, fill=(220, 220, 225))
    bar_y = y + 44
    bar_h = 22
    bar_w = EXTRAS_CANVAS_WIDTH - pad * 2
    draw.rounded_rectangle([(pad, bar_y), (EXTRAS_CANVAS_WIDTH - pad, bar_y + bar_h)], radius=bar_h // 2, fill=(50, 50, 62))
    _CP_OVERFLOW_COLOR = (255, 140, 60)
    overflow_tens = 0
    if cp_current is not None:
        if not cp_required:
            # some classes have no maximum - render the gauge as completely full.
            draw.rounded_rectangle([(pad, bar_y), (EXTRAS_CANVAS_WIDTH - pad, bar_y + bar_h)], radius=bar_h // 2, fill=(64, 200, 255))
        else:
            # gauge only has 10 segments, so cp_current wraps like an odometer:
            # the last digit fills the bar, the rest becomes a "+N" overflow badge.
            ones = cp_current % 10
            overflow_tens = cp_current // 10
            if overflow_tens > 0:
                draw.rounded_rectangle([(pad, bar_y), (EXTRAS_CANVAS_WIDTH - pad, bar_y + bar_h)], radius=bar_h // 2, fill=_CP_OVERFLOW_COLOR)
            fill_w = round(bar_w * ones / 10)
            if fill_w > 0:
                draw.rounded_rectangle([(pad, bar_y), (pad + fill_w, bar_y + bar_h)], radius=bar_h // 2, fill=(64, 200, 255))
    segments = 10
    seg_w = bar_w / segments
    for i in range(1, segments):
        sep_x = round(pad + seg_w * i)
        draw.line([(sep_x, bar_y + 2), (sep_x, bar_y + bar_h - 2)], fill=BACKGROUND_COLOR, width=2)
    if overflow_tens > 0:
        overflow_text = f"+{overflow_tens}"
        overflow_w = draw.textlength(overflow_text, font=FONT_BODY)
        draw.text((EXTRAS_CANVAS_WIDTH - pad - cp_text_w - overflow_w - 12, y + 10), overflow_text, font=FONT_BODY, fill=_CP_OVERFLOW_COLOR)
    y += _CP_SECTION_H

    # mile + mission section
    mile_text = f"{extras.mile_count:,} maimille" if extras.mile_count is not None else "- maimille"
    draw.text((pad, y + 4), mile_text, font=FONT_MILE, fill=(255, 221, 51))
    if extras.mission_deadline_text:
        deadline_w = draw.textlength(extras.mission_deadline_text, font=FONT_BODY_SMALL)
        draw.text((EXTRAS_CANVAS_WIDTH - pad - deadline_w, y + 6), extras.mission_deadline_text, font=FONT_BODY_SMALL, fill=(180, 180, 190))
    if extras.mission_clear_count is not None and extras.mission_total_count is not None:
        clear_text = f"CLEAR {extras.mission_clear_count}/{extras.mission_total_count}"
        draw.text((pad, y + 28), clear_text, font=FONT_BODY_SMALL, fill=(140, 220, 140))
    y += _MILE_HEADER_H

    _COMPLETE_YELLOW = (255, 221, 51)  # matches mile_text/reward accent yellow
    for mission in extras.missions:
        row_color = (40, 60, 44) if mission.cleared else (38, 38, 48)
        draw.rectangle([(pad, y + 2), (EXTRAS_CANVAS_WIDTH - pad, y + _MISSION_ROW_H - 6)], fill=row_color, outline=(55, 55, 68))
        check = "✓" if mission.cleared else "○"
        draw.text((pad + 12, y + 12), check, font=FONT_BODY, fill=_COMPLETE_YELLOW if mission.cleared else (120, 120, 130))
        text = "Complete!" if mission.cleared else (mission.text or "Complete previous mission to unlock!")
        text = _truncate_to_width(draw, text, FONT_BODY_SMALL, EXTRAS_CANVAS_WIDTH - pad * 2 - 150)
        draw.text((pad + 40, y + 13), text, font=FONT_BODY_SMALL, fill=_COMPLETE_YELLOW if mission.cleared else (150, 150, 158))
        if mission.mile_reward is not None:
            reward_text = f"+{mission.mile_reward} maimille"
            reward_w = draw.textlength(reward_text, font=FONT_BODY_SMALL)
            draw.text((EXTRAS_CANVAS_WIDTH - pad - 12 - reward_w, y + 13), reward_text, font=FONT_BODY_SMALL, fill=(255, 221, 51))
        y += _MISSION_ROW_H
    y += _SECTION_GAP

    # tickets section
    draw.text((pad, y), "TICKETS", font=FONT_SECTION_TITLE, fill=(255, 255, 255))
    y += _TICKETS_HEADER_H
    if not extras.tickets:
        draw.text((pad, y), "No tickets owned.", font=FONT_BODY_SMALL, fill=(150, 150, 158))
        y += _TICKET_ROW_H
    else:
        for ticket, img_bytes in zip(extras.tickets, ticket_image_bytes):
            used = _paste_scaled(image, img_bytes, (pad, y), 56)
            text_x = pad + used + (16 if used else 0)
            draw.text((text_x, y + 6), ticket.name, font=FONT_BODY_SMALL, fill=(220, 220, 225))
            count_text = f"×{ticket.count:,}" if ticket.count is not None else "×-"
            draw.text((text_x, y + 30), count_text, font=FONT_BODY_SMALL, fill=(180, 180, 190))
            y += _TICKET_ROW_H
    y += _SECTION_GAP

    intimate_text = f"Presents: {extras.intimate_count:,}" if extras.intimate_count is not None else "Presents: -"
    draw.text((pad, y), intimate_text, font=FONT_BODY, fill=(220, 220, 225))
    y += _INTIMATE_H

    _draw_footer(image, draw, canvas_h, EXTRAS_CANVAS_WIDTH)
    image.save(output, "PNG", compress_level=3)
    output.seek(0)


def render_profile_extras_template(output, *, mission_count: int = 5, ticket_count: int = 3) -> None:
    """Synchronous, no live data needed. Renders a transparent-background
    guide PNG at a representative "extras" /cc-profile canvas size (real
    height is data-dependent - mission/ticket counts vary per account, so
    this uses a representative count of each), with labeled outline boxes
    at every position render_profile_extras() actually draws content."""
    canvas_h = (
        _EXTRA_HEADER_H
        + _CP_SECTION_H
        + _MILE_HEADER_H
        + mission_count * _MISSION_ROW_H
        + _SECTION_GAP
        + _TICKETS_HEADER_H
        + max(ticket_count, 1) * _TICKET_ROW_H
        + _SECTION_GAP
        + _INTIMATE_H
        + FOOTER_HEIGHT
    )
    image = Image.new("RGBA", (EXTRAS_CANVAS_WIDTH, canvas_h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    pad = 24
    y = 0

    icon_y = (_EXTRA_HEADER_H - _EXTRA_ICON_SIZE) // 2
    _draw_guide_box(draw, (pad, icon_y, pad + _EXTRA_ICON_SIZE, icon_y + _EXTRA_ICON_SIZE), "ICON", color=(0, 200, 255))
    _draw_guide_box(draw, (pad + _EXTRA_ICON_SIZE + 16, 0, EXTRAS_CANVAS_WIDTH - pad, _EXTRA_HEADER_H), "PLAYER NAME")
    y += _EXTRA_HEADER_H

    _draw_guide_box(draw, (pad, y, EXTRAS_CANVAS_WIDTH - pad, y + _CP_SECTION_H), "CLASS POINT BAR + TEXT")
    y += _CP_SECTION_H

    _draw_guide_box(draw, (pad, y, EXTRAS_CANVAS_WIDTH - pad, y + _MILE_HEADER_H), "MAIMILLE + MISSION DEADLINE/CLEAR COUNT")
    y += _MILE_HEADER_H

    for i in range(mission_count):
        _draw_guide_box(draw, (pad, y + 2, EXTRAS_CANVAS_WIDTH - pad, y + _MISSION_ROW_H - 6), f"MISSION #{i + 1}", color=(0, 200, 255))
        y += _MISSION_ROW_H
    y += _SECTION_GAP

    _draw_guide_box(draw, (pad, y, EXTRAS_CANVAS_WIDTH - pad, y + _TICKETS_HEADER_H), "TICKETS HEADER")
    y += _TICKETS_HEADER_H
    for i in range(max(ticket_count, 1)):
        _draw_guide_box(draw, (pad, y, EXTRAS_CANVAS_WIDTH - pad, y + _TICKET_ROW_H - 4), f"TICKET #{i + 1}", color=(0, 200, 255))
        y += _TICKET_ROW_H
    y += _SECTION_GAP

    _draw_guide_box(draw, (pad, y, pad + 300, y + _INTIMATE_H), "PRESENTS COUNT")
    y += _INTIMATE_H

    _draw_guide_box(draw, (0, canvas_h - FOOTER_HEIGHT, EXTRAS_CANVAS_WIDTH, canvas_h), "FOOTER")

    image.save(output, "PNG", compress_level=3)
    output.seek(0)
