import io

from PIL import Image, ImageDraw, ImageFont

from circlechiffon.renderers.b50 import (
    CANVAS_WIDTH,
    FONT_DIR,
    FONT_FOOTER,
    FONT_HEADER_NAME,
    FONT_HEADER_STAT_LABEL,
    FONT_HEADER_STAT_VALUE,
    RATING_ACCENT_COLOR,
    _TIER_COLORS,
    _draw_guide_box,
    _fit_font,
    _hex_to_rgb,
    _paste_icon,
    _paste_rating_badge,
    _paste_scaled,
    _rounded_mask,
    _scale_to_height,
    _truncate_to_width,
)
from circlechiffon.types import Profile, ProfileExtras

_JP_BOLD = str(FONT_DIR / "NotoSansJP-Bold.ttf")
_JP_MEDIUM = str(FONT_DIR / "NotoSansJP-Medium.ttf")
_INTER_REGULAR = str(FONT_DIR / "Inter_28pt-Regular.ttf")
_INTER_BOLD = str(FONT_DIR / "Inter_28pt-Bold.ttf")

FONT_TIER_TITLE = ImageFont.truetype(_JP_BOLD, 16)
FONT_GRID_COUNT = ImageFont.truetype(_INTER_BOLD, 15)
FONT_GRID_LABEL = ImageFont.truetype(_INTER_REGULAR, 11)
FONT_SECTION_TITLE = ImageFont.truetype(_JP_BOLD, 20)
FONT_BODY = ImageFont.truetype(_JP_MEDIUM, 16)
FONT_BODY_SMALL = ImageFont.truetype(_JP_MEDIUM, 14)
FONT_MILE = ImageFont.truetype(_INTER_BOLD, 16)

BACKGROUND_COLOR = (24, 24, 32)
FOOTER_HEIGHT = 27
FOOTER_TEXT = "Generated by CiRCLE Chiffon - data from maimai DX NET // cc.etangaming.xyz // etan • etangaming123 • etangamingxyz"

HEADER_HEIGHT = 190
ICON_SIZE = 140

# clear-count grid: split into two side-by-side sub-grids instead of one
# 7x3 block, so rank/clear tiers (7 entries) and combo/sync/dxstar tiers
# (14 entries) read as two visually distinct groups rather than one
# undifferentiated block.
GRID_SUB_COLS = 7
GRID_GAP = 16
CELL_H = 108
COLUMN_WIDTH = (CANVAS_WIDTH - GRID_GAP) // 2
CELL_W = COLUMN_WIDTH // GRID_SUB_COLS
GRID_ROWS = 2  # combo/sync/dxstar column (14 entries / 7 per row) is the taller of the two

CANVAS_HEIGHT_CORE = HEADER_HEIGHT + GRID_ROWS * CELL_H + FOOTER_HEIGHT

# explicit (category, tag) order for the right sub-grid (combo/sync/dxstar) -
# the live page's own DOM order doesn't keep the 5 dxstar tiers contiguous,
# so they're pinned together here, with the bottom row ending on
# Full Sync, Sync Play, 5, 4, 3, 2, 1 as requested.
_RIGHT_COLUMN_ORDER = [
    ("combo", "fc"), ("combo", "fcp"), ("combo", "ap"), ("combo", "app"),
    ("sync", "fdxp"), ("sync", "fdx"), ("sync", "fsp"),
    ("sync", "fs"), ("sync", "sync"),
    ("dxstar", "5"), ("dxstar", "4"), ("dxstar", "3"), ("dxstar", "2"), ("dxstar", "1"),
]
_RIGHT_COLUMN_ORDER_INDEX = {key: i for i, key in enumerate(_RIGHT_COLUMN_ORDER)}


def _paste_icon_centered(
    base: Image.Image, icon_bytes: bytes | None, center_x: int, y: int, target_height: int, max_width: int | None = None
) -> int:
    """Like b50._paste_icon, but centers the pasted icon horizontally on
    center_x instead of anchoring its left edge at a fixed position. Badge
    plaques aren't square, so anchoring at `center_x - target_height / 2`
    (assuming pasted width always equals target_height) puts non-square
    icons visibly off-center - this computes the real post-resize width
    first. If `max_width` is given and the height-based width would exceed
    it, the icon is scaled down further (preserving aspect) to fit - some
    badge plaques (e.g. CLEAR) are wide enough that a height-only target
    still overflows a narrow grid cell. Returns the width used (0 if no
    icon)."""
    if not icon_bytes:
        return 0
    try:
        with Image.open(io.BytesIO(icon_bytes)) as icon:
            icon = icon.convert("RGBA")
            bbox = icon.getbbox()
            if bbox:
                icon = icon.crop(bbox)
            w = round(icon.width * target_height / icon.height)
            h = target_height
            if max_width is not None and w > max_width:
                h = round(h * max_width / w)
                w = max_width
            icon = icon.resize((w, h), Image.Resampling.LANCZOS)
            base.paste(icon, (round(center_x - w / 2), y), icon)
            return w
    except Exception:
        return 0


def _draw_footer(image: Image.Image, draw: ImageDraw.ImageDraw, canvas_h: int) -> None:
    footer_y = canvas_h - FOOTER_HEIGHT
    draw.rectangle([(0, footer_y), (CANVAS_WIDTH, canvas_h)], fill=(0, 0, 0, 120))
    draw.text((24, footer_y + 6), FOOTER_TEXT, font=FONT_FOOTER, fill=(200, 200, 205))


def _draw_title_capsule(
    image: Image.Image,
    draw: ImageDraw.ImageDraw,
    title: str | None,
    title_tier: str | None,
    pos: tuple[int, int],
    box_w: int,
    box_h: int,
) -> None:
    """Hand-drawn gradient capsule, same convention as /cc-display - the
    real site has no image asset for the title/trophy banner at all (it's
    CSS-styled text), so both renderers draw it instead of sourcing one."""
    x, y = pos
    _light_hex, mid_hex, dark_hex = _TIER_COLORS.get(title_tier or "", _TIER_COLORS["Gold"])
    radius = box_h // 2
    draw.rounded_rectangle([(x, y), (x + box_w, y + box_h)], radius=radius, fill=_hex_to_rgb(dark_hex))
    inset = 3
    draw.rounded_rectangle(
        [(x + inset, y + inset), (x + box_w - inset, y + box_h - inset)],
        radius=max(radius - inset, 2),
        fill=_hex_to_rgb(mid_hex),
    )
    if title:
        font = _fit_font(draw, title, _JP_BOLD, box_w - 24, box_h - 12)
        text_w = draw.textlength(title, font=font)
        text = title if text_w <= box_w - 24 else _truncate_to_width(draw, title, font, box_w - 24)
        text_w = draw.textlength(text, font=font)
        bbox = draw.textbbox((0, 0), text, font=font)
        text_h = bbox[3] - bbox[1]
        draw.text(
            (x + (box_w - text_w) / 2, y + (box_h - text_h) / 2 - bbox[1]),
            text,
            font=font,
            fill=_hex_to_rgb(dark_hex),
        )


def render_profile_core(
    *,
    profile: Profile,
    icon_bytes: bytes | None,
    course_rank_bytes: bytes | None,
    class_rank_bytes: bytes | None,
    rating_badge_bytes: bytes | None,
    badge_icons: dict[str, bytes],
    output,
) -> None:
    """Synchronous - CPU-bound Pillow work. Call via asyncio.to_thread().
    Matches the "core" stats shown on maimai DX NET's Player's Data page:
    name/title/rating/rank badges/star count/play counts, plus the full
    21-tier music clear-count grid. All image params are optional and
    degrade gracefully to a placeholder / text-only fallback."""
    badge_icons = badge_icons or {}
    image = Image.new("RGB", (CANVAS_WIDTH, CANVAS_HEIGHT_CORE), BACKGROUND_COLOR)
    draw = ImageDraw.Draw(image)

    pad = 24
    icon_x, icon_y = pad, (HEADER_HEIGHT - ICON_SIZE) // 2
    icon_mask = _rounded_mask((ICON_SIZE, ICON_SIZE), ICON_SIZE // 2)
    pasted_icon = False
    if icon_bytes:
        try:
            with Image.open(io.BytesIO(icon_bytes)) as src:
                scaled = _scale_to_height(src.convert("RGBA"), ICON_SIZE)
                left = max(0, (scaled.width - ICON_SIZE) // 2)
                cropped = scaled.crop((left, 0, left + ICON_SIZE, ICON_SIZE))
                image.paste(cropped, (icon_x, icon_y), icon_mask)
                pasted_icon = True
        except Exception:
            pasted_icon = False
    if not pasted_icon:
        placeholder = Image.new("RGB", (ICON_SIZE, ICON_SIZE), (200, 200, 205))
        image.paste(placeholder, (icon_x, icon_y), icon_mask)

    content_x = icon_x + ICON_SIZE + 20

    # right-aligned play-count stat blocks, same convention as b50's header
    stats = [("This Version", profile.current_version_plays), ("Total Plays", profile.total_plays)]
    stat_x = CANVAS_WIDTH - pad
    for label, value in reversed(stats):
        value_text = f"{value:,}" if value is not None else "-"
        value_w = draw.textlength(value_text, font=FONT_HEADER_STAT_VALUE)
        label_w = draw.textlength(label, font=FONT_HEADER_STAT_LABEL)
        block_w = max(value_w, label_w) + 30
        stat_x -= block_w
        draw.text((stat_x + (block_w - value_w) / 2, 46), value_text, font=FONT_HEADER_STAT_VALUE, fill=(255, 255, 255))
        draw.text((stat_x + (block_w - label_w) / 2, 86), label, font=FONT_HEADER_STAT_LABEL, fill=(180, 180, 190))

    name_max_w = max(40, stat_x - content_x - 16)
    name = _truncate_to_width(draw, profile.display_name, FONT_HEADER_NAME, name_max_w)
    draw.text((content_x, icon_y), name, font=FONT_HEADER_NAME, fill=(255, 255, 255))

    rating_text = str(profile.rating) if profile.rating is not None else "?"
    badge_h = 44
    badge_y = icon_y + 44
    rating_w = _paste_rating_badge(
        image, draw, rating_badge_bytes, rating_text, (content_x, badge_y), badge_h, RATING_ACCENT_COLOR
    )
    if rating_w == 0:
        draw.text((content_x, badge_y), f"Rating {rating_text}", font=FONT_HEADER_STAT_LABEL, fill=(200, 200, 205))

    badge_x = content_x + rating_w + 16
    used = _paste_scaled(image, course_rank_bytes, (badge_x, badge_y + 2), 36)
    badge_x += used + (12 if used else 0)
    _paste_scaled(image, class_rank_bytes, (badge_x, badge_y + 2), 36)

    # star count, small icon + count, below the rating/rank row
    star_y = badge_y + badge_h + 8
    star_x = content_x
    used = _paste_icon(image, badge_icons.get("misc:star"), (star_x, star_y), 22)
    star_x += used + (4 if used else 0)
    star_text = f"×{profile.star_count:,}" if profile.star_count is not None else "×-"
    draw.text((star_x, star_y + 2), star_text, font=FONT_HEADER_STAT_LABEL, fill=(220, 220, 225))

    # title capsule, bottom of the header band
    capsule_y = HEADER_HEIGHT - 42
    _draw_title_capsule(image, draw, profile.title, profile.title_tier, (content_x, capsule_y), 320, 34)

    # music clear-count grid - two side-by-side sub-grids grouped by
    # category rather than one flat 7x3 block: rank+clear tiers on the
    # left (7 entries, 1 row), combo/sync/dxstar tiers on the right (14
    # entries, 2 rows). Grouped by category rather than sliced by list
    # position since rank and clear aren't adjacent in the page's own
    # document order (rank, combo, sync, clear, dxstar).
    grid_top = HEADER_HEIGHT
    left_entries = [e for e in profile.music_counts if e.category in ("rank", "clear")]
    right_entries = sorted(
        (e for e in profile.music_counts if e.category in ("combo", "sync", "dxstar")),
        key=lambda e: _RIGHT_COLUMN_ORDER_INDEX.get((e.category, e.tag), len(_RIGHT_COLUMN_ORDER)),
    )
    for column_x0, entries in ((0, left_entries), (COLUMN_WIDTH + GRID_GAP, right_entries)):
        for i, entry in enumerate(entries):
            col = i % GRID_SUB_COLS
            row = i // GRID_SUB_COLS
            cell_x = column_x0 + col * CELL_W
            cell_y = grid_top + row * CELL_H
            draw.rectangle(
                [(cell_x + 2, cell_y + 2), (cell_x + CELL_W - 2, cell_y + CELL_H - 2)],
                fill=(38, 38, 48),
                outline=(55, 55, 68),
            )
            icon_bytes_for_tier = badge_icons.get(f"{entry.category}:{entry.tag}")
            icon_center_x = cell_x + CELL_W // 2
            # the CLEAR badge's source image is a much wider plaque than the
            # rank/combo/sync/dxstar icons, so pasting it at the same target
            # height as the rest makes it look oversized relative to its cell -
            # both a smaller target height and a hard width cap keep it in
            # proportion with the rest of the grid.
            icon_target_h = 24 if entry.category == "clear" else 40
            icon_max_w = 90 if entry.category == "clear" else None
            icon_y2 = cell_y + 16 + (40 - icon_target_h) // 2
            used = _paste_icon_centered(image, icon_bytes_for_tier, icon_center_x, icon_y2, icon_target_h, icon_max_w)
            if used == 0:
                # no icon available (e.g. remote fetch failed) - fall back to
                # a plain text tag label so the row still identifies its tier.
                label = entry.tag.upper()
                label_w = draw.textlength(label, font=FONT_GRID_LABEL)
                draw.text((cell_x + (CELL_W - label_w) / 2, icon_y2 + 14), label, font=FONT_GRID_LABEL, fill=(200, 200, 205))
            count_text = f"{entry.earned:,}/{entry.total:,}" if entry.earned is not None and entry.total is not None else "-"
            count_w = draw.textlength(count_text, font=FONT_GRID_COUNT)
            draw.text((cell_x + (CELL_W - count_w) / 2, cell_y + CELL_H - 26), count_text, font=FONT_GRID_COUNT, fill=(230, 230, 235))

    _draw_footer(image, draw, CANVAS_HEIGHT_CORE)
    image.save(output, "PNG", compress_level=3)
    output.seek(0)


_EXTRA_HEADER_H = 90
_EXTRA_ICON_SIZE = 64
_CP_SECTION_H = 90
_MILE_HEADER_H = 70
_MISSION_ROW_H = 46
_TICKETS_HEADER_H = 34
_TICKET_ROW_H = 76
_INTIMATE_H = 40
_SECTION_GAP = 14


def render_profile_core_template(output) -> None:
    """Synchronous, no live data needed. Renders a transparent-background
    guide PNG at the exact "core" /cc-profile canvas size, with labeled
    outline boxes at every position render_profile_core() actually draws
    content - including every grid cell, labeled by its (category, tag) -
    meant to be opened in an external image editor to design a background
    around the real content instead of guessing at its layout."""
    image = Image.new("RGBA", (CANVAS_WIDTH, CANVAS_HEIGHT_CORE), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    pad = 24
    icon_x, icon_y = pad, (HEADER_HEIGHT - ICON_SIZE) // 2
    _draw_guide_box(draw, (icon_x, icon_y, icon_x + ICON_SIZE, icon_y + ICON_SIZE), f"ICON {ICON_SIZE}x{ICON_SIZE}")

    content_x = icon_x + ICON_SIZE + 20
    stat_x = CANVAS_WIDTH - pad
    for label in ("Total Plays", "This Version"):
        block_w = 110
        stat_x -= block_w
        _draw_guide_box(draw, (stat_x, 40, stat_x + block_w, 100), f"STAT: {label}")

    _draw_guide_box(draw, (content_x, icon_y, stat_x - 16, icon_y + 34), "PLAYER NAME")

    badge_h = 44
    badge_y = icon_y + 44
    _draw_guide_box(draw, (content_x, badge_y, content_x + 150, badge_y + badge_h), "RATING BADGE", color=(0, 200, 255))
    badge_x = content_x + 150 + 16
    _draw_guide_box(draw, (badge_x, badge_y + 2, badge_x + 36, badge_y + 2 + 36), "COURSE RANK", color=(0, 200, 255))
    badge_x += 36 + 12
    _draw_guide_box(draw, (badge_x, badge_y + 2, badge_x + 36, badge_y + 2 + 36), "CLASS RANK", color=(0, 200, 255))

    star_y = badge_y + badge_h + 8
    _draw_guide_box(draw, (content_x, star_y, content_x + 120, star_y + 22), "STAR COUNT", color=(0, 200, 255))

    capsule_y = HEADER_HEIGHT - 42
    _draw_guide_box(draw, (content_x, capsule_y, content_x + 320, capsule_y + 34), "TITLE CAPSULE")

    # same category universe/order as the real render's left_entries (rank
    # tags in a representative ascending order, no live page to read the
    # real DOM order from) and right_entries (_RIGHT_COLUMN_ORDER, already
    # the exact real order).
    grid_top = HEADER_HEIGHT
    left_tags = [("rank", "s"), ("rank", "sp"), ("rank", "ss"), ("rank", "ssp"), ("rank", "sss"), ("rank", "sssp"), ("clear", "clear")]
    for column_x0, tags in ((0, left_tags), (COLUMN_WIDTH + GRID_GAP, _RIGHT_COLUMN_ORDER)):
        for i, (category, tag) in enumerate(tags):
            col = i % GRID_SUB_COLS
            row = i // GRID_SUB_COLS
            cell_x = column_x0 + col * CELL_W
            cell_y = grid_top + row * CELL_H
            _draw_guide_box(draw, (cell_x + 2, cell_y + 2, cell_x + CELL_W - 2, cell_y + CELL_H - 2), f"{category}:{tag}")

    _draw_guide_box(draw, (0, CANVAS_HEIGHT_CORE - FOOTER_HEIGHT, CANVAS_WIDTH, CANVAS_HEIGHT_CORE), "FOOTER")

    image.save(output, "PNG", compress_level=3)
    output.seek(0)


def render_profile_extras(
    *,
    profile: Profile,
    extras: ProfileExtras,
    icon_bytes: bytes | None,
    ticket_image_bytes: list[bytes | None],
    output,
) -> None:
    """Synchronous - CPU-bound Pillow work. Call via asyncio.to_thread().
    Renders CP progress, maimile count, missions, tickets, and intimate
    item count - fully separate from render_profile_core's stats, per the
    "extra" /cc-profile view (mutually exclusive with "core", not
    additive)."""
    canvas_h = (
        _EXTRA_HEADER_H
        + _CP_SECTION_H
        + _MILE_HEADER_H
        + len(extras.missions) * _MISSION_ROW_H
        + _SECTION_GAP
        + _TICKETS_HEADER_H
        + max(len(extras.tickets), 1) * _TICKET_ROW_H
        + _SECTION_GAP
        + _INTIMATE_H
        + FOOTER_HEIGHT
    )
    image = Image.new("RGB", (CANVAS_WIDTH, canvas_h), BACKGROUND_COLOR)
    draw = ImageDraw.Draw(image)

    pad = 24
    y = 0

    # header: icon + name only - no rating/title/ranks, this view is fully
    # separate from the core stats view.
    icon_mask = _rounded_mask((_EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE), _EXTRA_ICON_SIZE // 2)
    icon_y = (_EXTRA_HEADER_H - _EXTRA_ICON_SIZE) // 2
    pasted_icon = False
    if icon_bytes:
        try:
            with Image.open(io.BytesIO(icon_bytes)) as src:
                scaled = _scale_to_height(src.convert("RGBA"), _EXTRA_ICON_SIZE)
                left = max(0, (scaled.width - _EXTRA_ICON_SIZE) // 2)
                cropped = scaled.crop((left, 0, left + _EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE))
                image.paste(cropped, (pad, icon_y), icon_mask)
                pasted_icon = True
        except Exception:
            pasted_icon = False
    if not pasted_icon:
        placeholder = Image.new("RGB", (_EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE), (200, 200, 205))
        image.paste(placeholder, (pad, icon_y), icon_mask)
    draw.text((pad + _EXTRA_ICON_SIZE + 16, icon_y + 14), profile.display_name, font=FONT_HEADER_NAME, fill=(255, 255, 255))
    y += _EXTRA_HEADER_H

    # CP (class point) section - hand-drawn bar, no gauge/meter image asset
    # (the real site's version is CSS clip-rect masked, not a flat image).
    draw.text((pad, y + 6), "CLASS POINT", font=FONT_SECTION_TITLE, fill=(255, 255, 255))
    cp_current, cp_required = extras.cp_current, extras.cp_required
    cp_text = f"{cp_current if cp_current is not None else '-'} / {cp_required if cp_required is not None else '-'} CP"
    cp_text_w = draw.textlength(cp_text, font=FONT_BODY)
    draw.text((CANVAS_WIDTH - pad - cp_text_w, y + 10), cp_text, font=FONT_BODY, fill=(220, 220, 225))
    bar_y = y + 44
    bar_h = 22
    draw.rounded_rectangle([(pad, bar_y), (CANVAS_WIDTH - pad, bar_y + bar_h)], radius=bar_h // 2, fill=(50, 50, 62))
    if cp_current is not None and cp_required:
        frac = max(0.0, min(1.0, cp_current / cp_required))
        fill_w = round((CANVAS_WIDTH - pad * 2) * frac)
        if fill_w > 0:
            draw.rounded_rectangle([(pad, bar_y), (pad + fill_w, bar_y + bar_h)], radius=bar_h // 2, fill=(64, 200, 255))
    y += _CP_SECTION_H

    # mile + mission section
    mile_text = f"{extras.mile_count:,} maimille" if extras.mile_count is not None else "- maimille"
    draw.text((pad, y + 4), mile_text, font=FONT_MILE, fill=(255, 221, 51))
    if extras.mission_deadline_text:
        deadline_w = draw.textlength(extras.mission_deadline_text, font=FONT_BODY_SMALL)
        draw.text((CANVAS_WIDTH - pad - deadline_w, y + 6), extras.mission_deadline_text, font=FONT_BODY_SMALL, fill=(180, 180, 190))
    if extras.mission_clear_count is not None and extras.mission_total_count is not None:
        clear_text = f"CLEAR {extras.mission_clear_count}/{extras.mission_total_count}"
        draw.text((pad, y + 28), clear_text, font=FONT_BODY_SMALL, fill=(140, 220, 140))
    y += _MILE_HEADER_H

    for mission in extras.missions:
        row_color = (40, 60, 44) if mission.cleared else (38, 38, 48)
        draw.rectangle([(pad, y + 2), (CANVAS_WIDTH - pad, y + _MISSION_ROW_H - 6)], fill=row_color, outline=(55, 55, 68))
        check = "✓" if mission.cleared else "○"
        draw.text((pad + 12, y + 12), check, font=FONT_BODY, fill=(140, 220, 140) if mission.cleared else (120, 120, 130))
        text = mission.text or "(no description)"
        text = _truncate_to_width(draw, text, FONT_BODY_SMALL, CANVAS_WIDTH - pad * 2 - 150)
        draw.text((pad + 40, y + 13), text, font=FONT_BODY_SMALL, fill=(220, 220, 225) if mission.cleared else (150, 150, 158))
        if mission.mile_reward is not None:
            reward_text = f"+{mission.mile_reward} maimille"
            reward_w = draw.textlength(reward_text, font=FONT_BODY_SMALL)
            draw.text((CANVAS_WIDTH - pad - 12 - reward_w, y + 13), reward_text, font=FONT_BODY_SMALL, fill=(255, 221, 51))
        y += _MISSION_ROW_H
    y += _SECTION_GAP

    # tickets section
    draw.text((pad, y), "TICKETS", font=FONT_SECTION_TITLE, fill=(255, 255, 255))
    y += _TICKETS_HEADER_H
    if not extras.tickets:
        draw.text((pad, y), "No tickets owned.", font=FONT_BODY_SMALL, fill=(150, 150, 158))
        y += _TICKET_ROW_H
    else:
        for ticket, img_bytes in zip(extras.tickets, ticket_image_bytes):
            used = _paste_scaled(image, img_bytes, (pad, y), 56)
            text_x = pad + used + (16 if used else 0)
            draw.text((text_x, y + 6), ticket.name, font=FONT_BODY_SMALL, fill=(220, 220, 225))
            count_text = f"×{ticket.count:,}" if ticket.count is not None else "×-"
            draw.text((text_x, y + 30), count_text, font=FONT_BODY_SMALL, fill=(180, 180, 190))
            y += _TICKET_ROW_H
    y += _SECTION_GAP

    intimate_text = f"Presents: {extras.intimate_count:,}" if extras.intimate_count is not None else "Presents: -"
    draw.text((pad, y), intimate_text, font=FONT_BODY, fill=(220, 220, 225))
    y += _INTIMATE_H

    _draw_footer(image, draw, canvas_h)
    image.save(output, "PNG", compress_level=3)
    output.seek(0)


def render_profile_extras_template(output, *, mission_count: int = 5, ticket_count: int = 3) -> None:
    """Synchronous, no live data needed. Renders a transparent-background
    guide PNG at a representative "extras" /cc-profile canvas size (real
    height is data-dependent - mission/ticket counts vary per account, so
    this uses a representative count of each), with labeled outline boxes
    at every position render_profile_extras() actually draws content."""
    canvas_h = (
        _EXTRA_HEADER_H
        + _CP_SECTION_H
        + _MILE_HEADER_H
        + mission_count * _MISSION_ROW_H
        + _SECTION_GAP
        + _TICKETS_HEADER_H
        + max(ticket_count, 1) * _TICKET_ROW_H
        + _SECTION_GAP
        + _INTIMATE_H
        + FOOTER_HEIGHT
    )
    image = Image.new("RGBA", (CANVAS_WIDTH, canvas_h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    pad = 24
    y = 0

    icon_y = (_EXTRA_HEADER_H - _EXTRA_ICON_SIZE) // 2
    _draw_guide_box(draw, (pad, icon_y, pad + _EXTRA_ICON_SIZE, icon_y + _EXTRA_ICON_SIZE), "ICON", color=(0, 200, 255))
    _draw_guide_box(draw, (pad + _EXTRA_ICON_SIZE + 16, 0, CANVAS_WIDTH - pad, _EXTRA_HEADER_H), "PLAYER NAME")
    y += _EXTRA_HEADER_H

    _draw_guide_box(draw, (pad, y, CANVAS_WIDTH - pad, y + _CP_SECTION_H), "CLASS POINT BAR + TEXT")
    y += _CP_SECTION_H

    _draw_guide_box(draw, (pad, y, CANVAS_WIDTH - pad, y + _MILE_HEADER_H), "MAIMILLE + MISSION DEADLINE/CLEAR COUNT")
    y += _MILE_HEADER_H

    for i in range(mission_count):
        _draw_guide_box(draw, (pad, y + 2, CANVAS_WIDTH - pad, y + _MISSION_ROW_H - 6), f"MISSION #{i + 1}", color=(0, 200, 255))
        y += _MISSION_ROW_H
    y += _SECTION_GAP

    _draw_guide_box(draw, (pad, y, CANVAS_WIDTH - pad, y + _TICKETS_HEADER_H), "TICKETS HEADER")
    y += _TICKETS_HEADER_H
    for i in range(max(ticket_count, 1)):
        _draw_guide_box(draw, (pad, y, CANVAS_WIDTH - pad, y + _TICKET_ROW_H - 4), f"TICKET #{i + 1}", color=(0, 200, 255))
        y += _TICKET_ROW_H
    y += _SECTION_GAP

    _draw_guide_box(draw, (pad, y, pad + 300, y + _INTIMATE_H), "PRESENTS COUNT")
    y += _INTIMATE_H

    _draw_guide_box(draw, (0, canvas_h - FOOTER_HEIGHT, CANVAS_WIDTH, canvas_h), "FOOTER")

    image.save(output, "PNG", compress_level=3)
    output.seek(0)
