import io

from PIL import Image, ImageDraw, ImageFont

from circlechiffon.renderers.b50 import (
    CANVAS_WIDTH,
    FONT_DIR,
    FONT_FOOTER,
    FONT_HEADER_NAME,
    FONT_HEADER_STAT_LABEL,
    FONT_HEADER_STAT_VALUE,
    RATING_ACCENT_COLOR,
    _TIER_COLORS,
    _fit_font,
    _hex_to_rgb,
    _paste_icon,
    _paste_rating_badge,
    _paste_scaled,
    _rounded_mask,
    _scale_to_height,
    _truncate_to_width,
)
from circlechiffon.types import Profile, ProfileExtras

_JP_BOLD = str(FONT_DIR / "NotoSansJP-Bold.ttf")
_JP_MEDIUM = str(FONT_DIR / "NotoSansJP-Medium.ttf")
_INTER_REGULAR = str(FONT_DIR / "Inter_28pt-Regular.ttf")
_INTER_BOLD = str(FONT_DIR / "Inter_28pt-Bold.ttf")

FONT_TIER_TITLE = ImageFont.truetype(_JP_BOLD, 16)
FONT_GRID_COUNT = ImageFont.truetype(_INTER_BOLD, 15)
FONT_GRID_LABEL = ImageFont.truetype(_INTER_REGULAR, 11)
FONT_SECTION_TITLE = ImageFont.truetype(_JP_BOLD, 20)
FONT_BODY = ImageFont.truetype(_JP_MEDIUM, 16)
FONT_BODY_SMALL = ImageFont.truetype(_JP_MEDIUM, 14)
FONT_MILE = ImageFont.truetype(_INTER_BOLD, 16)

BACKGROUND_COLOR = (24, 24, 32)
FOOTER_HEIGHT = 27
FOOTER_TEXT = "Generated by CiRCLE Chiffon - data from maimai DX NET // cc.etangaming.xyz // etan • etangaming123 • etangamingxyz"

HEADER_HEIGHT = 190
ICON_SIZE = 140
GRID_COLS = 7
GRID_ROWS = 3  # 21 clear-count tiers, exactly 7x3
CELL_H = 108
CELL_W = CANVAS_WIDTH // GRID_COLS

CANVAS_HEIGHT_CORE = HEADER_HEIGHT + GRID_ROWS * CELL_H + FOOTER_HEIGHT


def _draw_footer(image: Image.Image, draw: ImageDraw.ImageDraw, canvas_h: int) -> None:
    footer_y = canvas_h - FOOTER_HEIGHT
    draw.rectangle([(0, footer_y), (CANVAS_WIDTH, canvas_h)], fill=(0, 0, 0, 120))
    draw.text((24, footer_y + 6), FOOTER_TEXT, font=FONT_FOOTER, fill=(200, 200, 205))


def _draw_title_capsule(
    image: Image.Image,
    draw: ImageDraw.ImageDraw,
    title: str | None,
    title_tier: str | None,
    pos: tuple[int, int],
    box_w: int,
    box_h: int,
) -> None:
    """Hand-drawn gradient capsule, same convention as /cc-display - the
    real site has no image asset for the title/trophy banner at all (it's
    CSS-styled text), so both renderers draw it instead of sourcing one."""
    x, y = pos
    _light_hex, mid_hex, dark_hex = _TIER_COLORS.get(title_tier or "", _TIER_COLORS["Gold"])
    radius = box_h // 2
    draw.rounded_rectangle([(x, y), (x + box_w, y + box_h)], radius=radius, fill=_hex_to_rgb(dark_hex))
    inset = 3
    draw.rounded_rectangle(
        [(x + inset, y + inset), (x + box_w - inset, y + box_h - inset)],
        radius=max(radius - inset, 2),
        fill=_hex_to_rgb(mid_hex),
    )
    if title:
        font = _fit_font(draw, title, _JP_BOLD, box_w - 24, box_h - 12)
        text_w = draw.textlength(title, font=font)
        text = title if text_w <= box_w - 24 else _truncate_to_width(draw, title, font, box_w - 24)
        text_w = draw.textlength(text, font=font)
        bbox = draw.textbbox((0, 0), text, font=font)
        text_h = bbox[3] - bbox[1]
        draw.text(
            (x + (box_w - text_w) / 2, y + (box_h - text_h) / 2 - bbox[1]),
            text,
            font=font,
            fill=_hex_to_rgb(dark_hex),
        )


def render_profile_core(
    *,
    profile: Profile,
    icon_bytes: bytes | None,
    course_rank_bytes: bytes | None,
    class_rank_bytes: bytes | None,
    rating_badge_bytes: bytes | None,
    badge_icons: dict[str, bytes],
    output,
) -> None:
    """Synchronous - CPU-bound Pillow work. Call via asyncio.to_thread().
    Matches the "core" stats shown on maimai DX NET's Player's Data page:
    name/title/rating/rank badges/star count/play counts, plus the full
    21-tier music clear-count grid. All image params are optional and
    degrade gracefully to a placeholder / text-only fallback."""
    badge_icons = badge_icons or {}
    image = Image.new("RGB", (CANVAS_WIDTH, CANVAS_HEIGHT_CORE), BACKGROUND_COLOR)
    draw = ImageDraw.Draw(image)

    pad = 24
    icon_x, icon_y = pad, (HEADER_HEIGHT - ICON_SIZE) // 2
    icon_mask = _rounded_mask((ICON_SIZE, ICON_SIZE), ICON_SIZE // 2)
    pasted_icon = False
    if icon_bytes:
        try:
            with Image.open(io.BytesIO(icon_bytes)) as src:
                scaled = _scale_to_height(src.convert("RGBA"), ICON_SIZE)
                left = max(0, (scaled.width - ICON_SIZE) // 2)
                cropped = scaled.crop((left, 0, left + ICON_SIZE, ICON_SIZE))
                image.paste(cropped, (icon_x, icon_y), icon_mask)
                pasted_icon = True
        except Exception:
            pasted_icon = False
    if not pasted_icon:
        placeholder = Image.new("RGB", (ICON_SIZE, ICON_SIZE), (200, 200, 205))
        image.paste(placeholder, (icon_x, icon_y), icon_mask)

    content_x = icon_x + ICON_SIZE + 20

    # right-aligned play-count stat blocks, same convention as b50's header
    stats = [("This Version", profile.current_version_plays), ("Total Plays", profile.total_plays)]
    stat_x = CANVAS_WIDTH - pad
    for label, value in reversed(stats):
        value_text = f"{value:,}" if value is not None else "-"
        value_w = draw.textlength(value_text, font=FONT_HEADER_STAT_VALUE)
        label_w = draw.textlength(label, font=FONT_HEADER_STAT_LABEL)
        block_w = max(value_w, label_w) + 30
        stat_x -= block_w
        draw.text((stat_x + (block_w - value_w) / 2, 46), value_text, font=FONT_HEADER_STAT_VALUE, fill=(255, 255, 255))
        draw.text((stat_x + (block_w - label_w) / 2, 86), label, font=FONT_HEADER_STAT_LABEL, fill=(180, 180, 190))

    name_max_w = max(40, stat_x - content_x - 16)
    name = _truncate_to_width(draw, profile.display_name, FONT_HEADER_NAME, name_max_w)
    draw.text((content_x, icon_y), name, font=FONT_HEADER_NAME, fill=(255, 255, 255))

    rating_text = str(profile.rating) if profile.rating is not None else "?"
    badge_h = 44
    badge_y = icon_y + 44
    rating_w = _paste_rating_badge(
        image, draw, rating_badge_bytes, rating_text, (content_x, badge_y), badge_h, RATING_ACCENT_COLOR
    )
    if rating_w == 0:
        draw.text((content_x, badge_y), f"Rating {rating_text}", font=FONT_HEADER_STAT_LABEL, fill=(200, 200, 205))

    badge_x = content_x + rating_w + 16
    used = _paste_scaled(image, course_rank_bytes, (badge_x, badge_y + 2), 36)
    badge_x += used + (12 if used else 0)
    _paste_scaled(image, class_rank_bytes, (badge_x, badge_y + 2), 36)

    # star count, small icon + count, below the rating/rank row
    star_y = badge_y + badge_h + 8
    star_x = content_x
    used = _paste_icon(image, badge_icons.get("misc:star"), (star_x, star_y), 22)
    star_x += used + (4 if used else 0)
    star_text = f"×{profile.star_count:,}" if profile.star_count is not None else "×-"
    draw.text((star_x, star_y + 2), star_text, font=FONT_HEADER_STAT_LABEL, fill=(220, 220, 225))

    # title capsule, bottom of the header band
    capsule_y = HEADER_HEIGHT - 42
    _draw_title_capsule(image, draw, profile.title, profile.title_tier, (content_x, capsule_y), 320, 34)

    # music clear-count grid - 7x3, one cell per Profile.music_counts entry
    # in its existing (already-correct, page-matching) document order.
    grid_top = HEADER_HEIGHT
    for i, entry in enumerate(profile.music_counts):
        col = i % GRID_COLS
        row = i // GRID_COLS
        cell_x = col * CELL_W
        cell_y = grid_top + row * CELL_H
        draw.rectangle(
            [(cell_x + 2, cell_y + 2), (cell_x + CELL_W - 2, cell_y + CELL_H - 2)],
            fill=(38, 38, 48),
            outline=(55, 55, 68),
        )
        icon_bytes_for_tier = badge_icons.get(f"{entry.category}:{entry.tag}")
        icon_x2 = cell_x + (CELL_W - 40) // 2
        icon_y2 = cell_y + 10
        used = _paste_icon(image, icon_bytes_for_tier, (icon_x2, icon_y2), 40)
        if used == 0:
            # no icon available (e.g. remote fetch failed) - fall back to
            # a plain text tag label so the row still identifies its tier.
            label = entry.tag.upper()
            label_w = draw.textlength(label, font=FONT_GRID_LABEL)
            draw.text((cell_x + (CELL_W - label_w) / 2, icon_y2 + 14), label, font=FONT_GRID_LABEL, fill=(200, 200, 205))
        count_text = f"{entry.earned:,}/{entry.total:,}" if entry.earned is not None and entry.total is not None else "-"
        count_w = draw.textlength(count_text, font=FONT_GRID_COUNT)
        draw.text((cell_x + (CELL_W - count_w) / 2, cell_y + CELL_H - 26), count_text, font=FONT_GRID_COUNT, fill=(230, 230, 235))

    _draw_footer(image, draw, CANVAS_HEIGHT_CORE)
    image.save(output, "PNG", compress_level=3)
    output.seek(0)


_EXTRA_HEADER_H = 90
_EXTRA_ICON_SIZE = 64
_CP_SECTION_H = 90
_MILE_HEADER_H = 70
_MISSION_ROW_H = 46
_TICKETS_HEADER_H = 34
_TICKET_ROW_H = 76
_INTIMATE_H = 40
_SECTION_GAP = 14


def render_profile_extras(
    *,
    profile: Profile,
    extras: ProfileExtras,
    icon_bytes: bytes | None,
    ticket_image_bytes: list[bytes | None],
    output,
) -> None:
    """Synchronous - CPU-bound Pillow work. Call via asyncio.to_thread().
    Renders CP progress, maimile count, missions, tickets, and intimate
    item count - fully separate from render_profile_core's stats, per the
    "extra" /cc-profile view (mutually exclusive with "core", not
    additive)."""
    canvas_h = (
        _EXTRA_HEADER_H
        + _CP_SECTION_H
        + _MILE_HEADER_H
        + len(extras.missions) * _MISSION_ROW_H
        + _SECTION_GAP
        + _TICKETS_HEADER_H
        + max(len(extras.tickets), 1) * _TICKET_ROW_H
        + _SECTION_GAP
        + _INTIMATE_H
        + FOOTER_HEIGHT
    )
    image = Image.new("RGB", (CANVAS_WIDTH, canvas_h), BACKGROUND_COLOR)
    draw = ImageDraw.Draw(image)

    pad = 24
    y = 0

    # header: icon + name only - no rating/title/ranks, this view is fully
    # separate from the core stats view.
    icon_mask = _rounded_mask((_EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE), _EXTRA_ICON_SIZE // 2)
    icon_y = (_EXTRA_HEADER_H - _EXTRA_ICON_SIZE) // 2
    pasted_icon = False
    if icon_bytes:
        try:
            with Image.open(io.BytesIO(icon_bytes)) as src:
                scaled = _scale_to_height(src.convert("RGBA"), _EXTRA_ICON_SIZE)
                left = max(0, (scaled.width - _EXTRA_ICON_SIZE) // 2)
                cropped = scaled.crop((left, 0, left + _EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE))
                image.paste(cropped, (pad, icon_y), icon_mask)
                pasted_icon = True
        except Exception:
            pasted_icon = False
    if not pasted_icon:
        placeholder = Image.new("RGB", (_EXTRA_ICON_SIZE, _EXTRA_ICON_SIZE), (200, 200, 205))
        image.paste(placeholder, (pad, icon_y), icon_mask)
    draw.text((pad + _EXTRA_ICON_SIZE + 16, icon_y + 14), profile.display_name, font=FONT_HEADER_NAME, fill=(255, 255, 255))
    y += _EXTRA_HEADER_H

    # CP (class point) section - hand-drawn bar, no gauge/meter image asset
    # (the real site's version is CSS clip-rect masked, not a flat image).
    draw.text((pad, y + 6), "CLASS POINT", font=FONT_SECTION_TITLE, fill=(255, 255, 255))
    cp_current, cp_required = extras.cp_current, extras.cp_required
    cp_text = f"{cp_current if cp_current is not None else '-'} / {cp_required if cp_required is not None else '-'} CP"
    cp_text_w = draw.textlength(cp_text, font=FONT_BODY)
    draw.text((CANVAS_WIDTH - pad - cp_text_w, y + 10), cp_text, font=FONT_BODY, fill=(220, 220, 225))
    bar_y = y + 44
    bar_h = 22
    draw.rounded_rectangle([(pad, bar_y), (CANVAS_WIDTH - pad, bar_y + bar_h)], radius=bar_h // 2, fill=(50, 50, 62))
    if cp_current is not None and cp_required:
        frac = max(0.0, min(1.0, cp_current / cp_required))
        fill_w = round((CANVAS_WIDTH - pad * 2) * frac)
        if fill_w > 0:
            draw.rounded_rectangle([(pad, bar_y), (pad + fill_w, bar_y + bar_h)], radius=bar_h // 2, fill=(64, 200, 255))
    y += _CP_SECTION_H

    # mile + mission section
    mile_text = f"{extras.mile_count:,} Mile" if extras.mile_count is not None else "- Mile"
    draw.text((pad, y + 4), mile_text, font=FONT_MILE, fill=(255, 221, 51))
    if extras.mission_deadline_text:
        deadline_w = draw.textlength(extras.mission_deadline_text, font=FONT_BODY_SMALL)
        draw.text((CANVAS_WIDTH - pad - deadline_w, y + 6), extras.mission_deadline_text, font=FONT_BODY_SMALL, fill=(180, 180, 190))
    if extras.mission_clear_count is not None and extras.mission_total_count is not None:
        clear_text = f"CLEAR {extras.mission_clear_count}/{extras.mission_total_count}"
        draw.text((pad, y + 28), clear_text, font=FONT_BODY_SMALL, fill=(140, 220, 140))
    y += _MILE_HEADER_H

    for mission in extras.missions:
        row_color = (40, 60, 44) if mission.cleared else (38, 38, 48)
        draw.rectangle([(pad, y + 2), (CANVAS_WIDTH - pad, y + _MISSION_ROW_H - 6)], fill=row_color, outline=(55, 55, 68))
        check = "✓" if mission.cleared else "○"
        draw.text((pad + 12, y + 12), check, font=FONT_BODY, fill=(140, 220, 140) if mission.cleared else (120, 120, 130))
        text = mission.text or "(no description)"
        text = _truncate_to_width(draw, text, FONT_BODY_SMALL, CANVAS_WIDTH - pad * 2 - 150)
        draw.text((pad + 40, y + 13), text, font=FONT_BODY_SMALL, fill=(220, 220, 225) if mission.cleared else (150, 150, 158))
        if mission.mile_reward is not None:
            reward_text = f"+{mission.mile_reward} Mile"
            reward_w = draw.textlength(reward_text, font=FONT_BODY_SMALL)
            draw.text((CANVAS_WIDTH - pad - 12 - reward_w, y + 13), reward_text, font=FONT_BODY_SMALL, fill=(255, 221, 51))
        y += _MISSION_ROW_H
    y += _SECTION_GAP

    # tickets section
    draw.text((pad, y), "TICKETS", font=FONT_SECTION_TITLE, fill=(255, 255, 255))
    y += _TICKETS_HEADER_H
    if not extras.tickets:
        draw.text((pad, y), "No tickets owned.", font=FONT_BODY_SMALL, fill=(150, 150, 158))
        y += _TICKET_ROW_H
    else:
        for ticket, img_bytes in zip(extras.tickets, ticket_image_bytes):
            used = _paste_scaled(image, img_bytes, (pad, y), 56)
            text_x = pad + used + (16 if used else 0)
            draw.text((text_x, y + 6), ticket.name, font=FONT_BODY_SMALL, fill=(220, 220, 225))
            count_text = f"×{ticket.count:,}" if ticket.count is not None else "×-"
            draw.text((text_x, y + 30), count_text, font=FONT_BODY_SMALL, fill=(180, 180, 190))
            y += _TICKET_ROW_H
    y += _SECTION_GAP

    intimate_text = f"Intimate Items: {extras.intimate_count:,}" if extras.intimate_count is not None else "Intimate Items: -"
    draw.text((pad, y), intimate_text, font=FONT_BODY, fill=(220, 220, 225))
    y += _INTIMATE_H

    _draw_footer(image, draw, canvas_h)
    image.save(output, "PNG", compress_level=3)
    output.seek(0)
